# .github/workflows/sample.yml
name: Sample Workflow

on: [push, workflow_dispatch]

jobs:
  hello:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'PRODUCTION' || github.ref_name == 'staging' && 'STAGING' || 'SANDBOX'}}
    steps:
      - name: Echo hello world
        run: echo "hello world"
      - name: Echo secret
        run: echo "${{ secrets.MY_SECRET }}"
      - name: Echo Env Secret
        run: echo "${{ secrets.ENV_SECRET }}"