# .github/workflows/sample.yml
name: Sample Workflow

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello world
        run: echo "hello world"
      - name: Echo secret
        run: echo "${{ secrets.secret }}"